server:
  port: 8001
  
spring:
  application:
    name: sso-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sso_db?serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.209.101
    port: 6379
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
      
mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.tedu.sso.pojo
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    
ribbon:
  eureka:
    enabled: true
    
logging:
  level:
    com.tedu.sso.mapper: debug